---

- hosts: localhost
  vars:
    url_ova: https://github.com/shirishshukla/sks_test/blob/master/test/test.ova
    url_hostname: github.com

  tasks:
   ## your code form here
    - name: Is url have valid hostname
      assert:
        that:
          - url_hostname == url_ova_hostname
        fail_msg: "URL: {{ url_ova }} does not have valid hostname {{ url_hostname }}"
        success_msg: "URL: {{ url_ova }} have valid hostname {{ url_hostname }}"
      vars:
        url_ova_hostname: "{{ url_ova.split('/')[2] }}"

    - name: Is url file have valid .ova extension
      assert:
        that:
          - url_ova_file.endswith(url_ova_file_ext)
        fail_msg: "URL: {{ url_ova }} file {{ url_ova_file }} extension is not {{ url_ova_file_ext }}"
        success_msg: "URL: {{ url_ova }} file {{ url_ova_file }} extension is {{ url_ova_file_ext }}"
      vars:
        url_ova_file: "{{ url_ova.split('/')[-1] }}"
        url_ova_file_ext: ".ova"

    - name: Is URL accessible with 200 status code
      uri:
        url: "{{ url_ova }}"
        method: GET
        status_code: [200]
      register: _result
      until: _result.status == 200
      retries: 18 # 18 x 10 seconds = 180 (3.0 mins)
      delay: 10

## END
