#!/bin/bash

cleanupFolder='/appllogs/backup/'
emailTO='chandru.perumal@cvshealth.com'
emailTxtFile='/tmp/email_text.txt'
cleanupFilesList='/tmp/clean_files.txt'

cd $cleanupFolder
echo "Before Clean up -> df -h | grep app_vg" > $emailTxtFile
df -h | grep app_vg >> $emailTxtFile
find $cleanupFolder -name "*.zip" -exec ls -ltr {} \; > $cleanupFilesList
if [[ -s $cleanupFilesList ]]; then
    echo -e "Number of files to be cleanup - \c" >> $emailTxtFile
    cat $cleanupFilesList | wc -l >> $emailTxtFile
    echo -e "\nList of files to be cleaned up - " >> $emailTxtFile
    cat $cleanupFilesList >> $emailTxtFile
    echo >> $emailTxtFile
    find $cleanupFolder -name "*.zip" -exec rm -rf {} \;
    if [ $? -eq 0 ]; then
        echo "After Clean up -> df -h | grep app_vg" >> $emailTxtFile
        df -h | grep app_vg >> $emailTxtFile
        echo $emailTxtFile | mailx -s "File System Log Cleanup from $(uname -n)" $emailTO
    else
        echo -e "\nCleanUp failed. Please check manually. Exiting." >> $emailTxtFile
        echo $emailTxtFile | mailx -s "File System Log Cleanup from $(uname -n)" $emailTO
    fi
else
    echo "No Files for Cleanup" >> $emailTxtFile
    echo $emailTxtFile | mailx -s "File System Log Cleanup from $(uname -n)" $emailTO
fi 
rm $emailTxtFile $cleanupFilesList
