---

image:
  name: bitnami/kubectl
  entrypoint: [""]

include:
  - local: k8s/Base.latest.loader.gitlab-ci.yml

stages:
  - initialize
  - validate
  - build
  - deploy
  - test
  - cleanup

initialize:
  extends: .initialize

validate:
  extends: .validate

build:
  extends: .build

deploy:
  extends: .deploy
  dependencies:
    - build

test:
  extends: .test
  dependencies:
    - deploy

cleanup:
  extends: .destroy
  dependencies:
    - deploy

## END
