name: Generate Random Number1

#echo "CUSTOM_VAR=$(printf '{\"hostname\":\"%s\",\"distro\":\"%s\",\"uptime\":\"%s\"}\n' \"$hostname\" \"$distro\" \"$uptime\")" >> $GITHUB_ENV
        
on:
  push:
    branches:
      - master

jobs:
  generate_random_number:
    runs-on: ubuntu-latest

    steps:
      - name: Set ENV var
        run: |
          MY_STRING=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
          echo "VAR1=$MY_STRING" >>  >> $GITHUB_ENV

      - name: Use ENV var via `env` block
        run: |
          echo ${{env.CUSTOM_VAR}} # OK
