name: Generate Random Number1

on:
  push:
    branches:
      - master

jobs:
  generate_random_number:
    runs-on: ubuntu-latest

    steps:
    - name: Generate Random Number
      id: s1
      run: |
        echo "RANDOMNUMBER=$((RANDOM % 100))"
        echo "RANDOMNUMBER=$RANDOMNUMBER" >> $GITHUB_ENV
        echo hello -1 - $RANDOMNUMBER
      set-output:
          name: OUT1
          value: ${{ steps.s1.outputs.RANDOMNUMBER }}
    - name: Read Output
      run: |
        echo hello -2- $OUT1
