name: Generate Random Number1

on:
  push:
    branches:
      - master

jobs:
  generate_random_number:
    runs-on: ubuntu-latest

    steps:
    - name: Generate Random Number
      run: |
        echo "RANDOM_NUMBER=$((RANDOM % 100))"
        echo $RANDOM_NUMBER > github_output1.txt
    - name: Read Output
      run: |
        read RANDOM_NUMBER < github_output1.txt
        echo $RANDOM_NUMBER > random-number.txt
        echo hello ...$RANDOM_NUMBER
