name: Generate Random Number1

#echo "CUSTOM_VAR=$(printf '{\"hostname\":\"%s\",\"distro\":\"%s\",\"uptime\":\"%s\"}\n' \"$hostname\" \"$distro\" \"$uptime\")" >> $GITHUB_ENV
        
on:
  push:
    branches:
      - master

jobs:
  generate_random_number:
    runs-on: ubuntu-latest

    steps:
      - name: Set ENV var
        run: |
          ls > test1.txt
          cat test1.txt

      - name: Use ENV var via `env` block
        run: |
          hello=$(cat test1.txt)
          echo ... $hello
