name: Generate Random Number1

#echo "CUSTOM_VAR=$(printf '{\"hostname\":\"%s\",\"distro\":\"%s\",\"uptime\":\"%s\"}\n' \"$hostname\" \"$distro\" \"$uptime\")" >> $GITHUB_ENV
        
on:
  push:
    branches:
      - master
env:
  SVC_NET_CONF: "{\"awsvpcConfiguration\":{\"subnets\":[\"subnet-0c635e43566c97d4c\",\"subnet-0e145f3b7a7958f0e\"],\"securityGroups\":[\"sg-0093de3601375a5bb\"],\"assignPublicIp\":\"ENABLED\"}}"
jobs:
  generate_random_number:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Random Number
      id: s1
      run: |
        RANDOMNUMBER=$(curl --location https://cat-fact.herokuapp.com/facts/|jq -c)
        echo "RANDOMNUMBER=$RANDOMNUMBER" >> $GITHUB_ENV
        echo hello -1 - $RANDOMNUMBER
    - name: Read Output
      run: |
        echo ${SVC_NET_CONF}
        ls $SVC_NET_CONF
