name: Generate Random Number1

on:
  push:
    branches:
      - master

jobs:
  generate_random_number:
    runs-on: ubuntu-latest

    steps:
      - name: Set ENV var
        run: |
          echo "CUSTOM_VAR=$(pwd)" >> $GITHUB_ENV

      - name: Use ENV var via `env` block
        run: |
          echo ${{env.CUSTOM_VAR}} # OK
